# Generated by Django 4.2 on 2026-04-28 22:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20, unique=True)),
                ('course_title', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('semester', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('credits', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('lecture_hours', models.IntegerField(default=3)),
                ('tutorial_hours', models.IntegerField(default=0)),
                ('practical_hours', models.IntegerField(default=0)),
                ('self_learning_hours', models.IntegerField(default=1)),
                ('total_hours', models.IntegerField(default=40)),
                ('cie_marks', models.IntegerField(default=50)),
                ('see_marks', models.IntegerField(default=50)),
                ('exam_duration', models.IntegerField(default=3)),
                ('prerequisites', models.TextField(blank=True)),
                ('course_objectives', models.TextField()),
                ('course_outcomes', models.JSONField(default=list)),
                ('modules', models.JSONField(default=list)),
                ('hands_on_exercises', models.JSONField(default=list)),
                ('self_learning_topics', models.JSONField(default=list)),
                ('rbt_levels', models.JSONField(default=dict)),
                ('textbooks', models.JSONField(default=list)),
                ('references', models.JSONField(default=list)),
                ('num_cos', models.IntegerField(default=5)),
                ('copo_mapping', models.JSONField(default=dict)),
                ('teaching_methods', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', '📝 Draft'), ('pending_bos', '⏳ Pending BOS Approval'), ('pending_hod', '⏳ Pending HOD Approval'), ('approved', '✅ Approved'), ('rejected', '❌ Rejected'), ('revision', '🔄 Revision Required')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bos_approved', models.BooleanField(default=False)),
                ('bos_approved_at', models.DateTimeField(blank=True, null=True)),
                ('bos_comments', models.TextField(blank=True)),
                ('hod_approved', models.BooleanField(default=False)),
                ('hod_approved_at', models.DateTimeField(blank=True, null=True)),
                ('hod_comments', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='syllabi_pdfs/')),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True)),
                ('bos_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bos_approved_courses', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_courses', to=settings.AUTH_USER_MODEL)),
                ('hod_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_approved_courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='curriculum.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
